use_frameworks!

platform :ios, '11.0'

target 'QMLineUI_Example' do
  pod 'QMLineUI', :path => '../'

#  pod 'QMLineSDK', :path => '../QMLineSDK/'
 pod 'SocketRocket', '~> 0.6.0'
  pod 'JSONModel'
  pod 'libmp3lame', '~> 3.99.5'
  pod 'QMLinezcTest'
end

#post_install do |installer|
#  installer.pods_project.targets.each do |target|
#    target.build_configurations.each do |config|
#      config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '9.0'
#      end
#    end
#  end
